
services:
  chromadb:
    image: chromadb/chroma
    restart: unless-stopped
    volumes:
      - ${DB}:/data
    ports:
      - 8000:8000
    networks:
      - botnet
  theaugur-1:
    container_name: 'theaugur-1'
    build:
      context: .
    image: ghcr.io/ryanmcgreevy/augur:latest
    restart: unless-stopped
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CHROMA_URL: chromadb
      CHROMA_PORT: 8000
      SHARD_COUNT: 1
      SHARD_ID: 0
    volumes:
      - ${STORE_LOCATION}:/app/store_location
    depends_on:
      chromadb:
        condition: service_started
    networks:
      - botnet
  # theaugur-2:
  #   container_name: 'theaugur-2'
  #   environment:
  #     SHARD_ID: 1
  #   extends:
  #     service: theaugur-1
  crawler:
    build:
      context: ./utils/
    image: ghcr.io/ryanmcgreevy/augur-crawler:latest
    restart: unless-stopped
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CHROMA_URL: chromadb
      CHROMA_PORT: 8000
      ESO_NEWS: ${ESO_NEWS}
    volumes:
      - ${STORE_LOCATION}:/app/store_location
      - ${ESO_NEWS}:/app/eso_news
    depends_on:
      chromadb:
        condition: service_started
    networks:
      - botnet
networks:
  botnet:
    driver: bridge
volumes:
  db:
    external: true
  store_location:
    external: true
  eso_news:
    external: true
      