name: deploy

on: 
  push:
    branches: [ main ]
  
jobs :

  build: 
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: build
        env:
          DB: /mnt/ssd/db
          STORE_LOCATION: /mnt/ssd/store_location
          ESO_NEWS: /mnt/ssd/eso_news
        run: docker compose build
      - name: deploy
        env:
          DB: /mnt/ssd/db
          STORE_LOCATION: /mnt/ssd/store_location
          ESO_NEWS: /mnt/ssd/eso_news
        run: docker compose up -d
