name: deploy

on: 
  push:
    branches: [ main ]
  
jobs :

  build: 
    runs-on: self-hosted
    env:
      DB: /root/db
      STORE_LOCATION: /root/store_location
      ESO_NEWS: /root/eso_news
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: docker compose build
      - name: deploy
        run: docker compose up -d
